### ISSUE TITLE
problem about Gapmind  at PHASE 1

### ISSUE THREAD

**Issue by ye00ye** [morgannprice/PaperBLAST#10]
Hello, I want to generate curated database according to gaps/SETUP PHASE 1
I clone the whold program, then  I  download PaperBLAST database and uniprot_sprot.dat.gz, and put them into data/ and ind/ directory respectively.
then I executed the command  "bin/setupGaps.pl  -ind ind -set carbon -data data", the terminate said that:
        No such file: data/../sprot.curated_parsed -- use -sprot to change

then I changed the command "bin/setupGaps.pl  -ind ind -set carbon -data data -sprot gaps/carbon", the terminate said that:
        /data1/huangqiang_test/linshi_20240114/PaperBLAST/bin/curatedFaa.pl -db data/litsearch.db -uniq data/uniq.faa -out tmp/path.carbon/curated.faa -curatedids
        DBD::SQLite::db selectall_arrayref failed: no such table: CuratedGene at /data1/huangqiang_test/linshi_20240114/PaperBLAST/bin/curatedFaa.pl line 38.
        DBD::SQLite::db selectall_arrayref failed: no such table: CuratedGene at /data1/huangqiang_test/linshi_20240114/PaperBLAST/bin/curatedFaa.pl line 38.
        Error running /data1/huangqiang_test/linshi_20240114/PaperBLAST/bin/curatedFaa.pl -db data/litsearch.db -uniq data/uniq.faa -out tmp/path.carbon/curated.faa -curatedids
        1337770!n at bin/setupGaps.pl line 87

could you please tell me how to execute the command rightly, thanks

**Comment by morgannprice** [comment]
The sprot.curated_parsed file can be created by running the bin/sprotCharacterized.pl command, i.e.

zcat ind/uniprot_sprot.dat.gz | bin/sprotCharacterized.pl > sprot.curated_parsed

This should have been in gaps/SETUP, which is now updated.
