### ISSUE TITLE
Result of the Phase 3

### ISSUE THREAD

**Issue by Oceazh** [morgannprice/PaperBLAST#14]
Hello, dear GapMind team.

Thank you for developing this useful tool GapMind, it helps us a lot in our work!

I managed to run gapmind locally, but I noticed that the result was formatted differently than the output of an online submit, so I was confused about the result file. Firstly, which of the three files **aa.sum.cand, aa.sum.rules** and **aa.sum.steps** should I select for analysis? Secondly, in terms of the reliability of the results, which indicators should I select for screening? I would appreciate it very much if you could answer my questions.

**Comment by morgannprice** [comment]
The *.sum files are tab-delimited. aa.sum.rules has one line per rule and pathway. Usually I look only at the top-level rule for each pathway (rule = "all"). nHi, nMed, and nLo show the total number of high-confidence, medium-confidence, and low-confidence steps. In particular, if nMed = 0 and nLo = 0 that means that every step in the pathway is high-confidence, and the entire pathway can be considered high confidence. If there are no low-confidence steps (nLo=0), or if the only low-confidence steps are known gaps, then the pathway is probably present. expandedPath has the list of steps for the highest-confidence path.

aa.sum.steps has one line per step; look there to see what the actual best candidates are. For more details about the scoring of the candidates, see aa.sum.cand, which has one row per candidate for each step.
 
If you're interested in known gaps, then aa.sum.knownsim will report which organisms in your data set ("orgId") are similar to organisms with known gaps ("orgId2"). For the actual known gaps see gaps/aa/aa,known.steps.gaps and gaps/aa/aa.known.gaps.orgs (both tab-delimited).

-- Morgan

**Comment by morgannprice** [comment]
I added this information to gaps/SETUP
