### ISSUE TITLE
Issue with buildorgs.pl to set up many genomes at once

### ISSUE THREAD

**Issue by Oceazh** [morgannprice/PaperBLAST#15]
Hello, dear GapMind team.

Thank you for developing this useful tool GapMind, it helps us a lot in our work!

I noticed that it is available to use buildorgs.pl to set up many genomes at once, but what changes to the code would be required. 
Code : bin/buildorgs.pl -out tmp/DvH/orgs -orgs 'file:GCF_902167245.1_DSV_KAUST_v1_protein.faa:Desulfovibrio vulgaris downloaded'

**Comment by morgannprice** [comment]
You can specify multiple arguments to -orgs, or you can specify -orgfile which should have one organism specifier per line (or comment lines that start with "#"). Run

./buildorgs.pl -help

for more information.
