### ISSUE TITLE
extend with foldseek?

### ISSUE THREAD

**Issue by karchern** [morgannprice/PaperBLAST#17]
Hi Morgan,

thanks for your great work in paperblast and the rest of your functional annotation toolkit!

Do you have any plan to enhance the search step with structure-based homology searches such as foldseek? While slower than blast, I envision it could be a useful flag that users could set if they want more sensitive searches than blast.

Thanks :)

**Comment by morgannprice** [comment]
To find more remote homologs, PaperBLAST and SitesBLAST already support HMM searches. You can convert a protein sequence into an HMM-based profile using EBI's HMMer server.

http://www.ebi.ac.uk/Tools/hmmer/

Also, most proteins belongs to known families in InterPro or CDD that are described using HMMs (see the PaperBLAST links). In particular, you can type an PFam or TIGRFam identifier into the PaperBLAST or SitesBLAST web site.

My intuition is that even more remote homologs are unlikely to have conserved functions unless functional residues are conserved. I'm considering how to integrate FoldSeek with SitesBLAST. In the meantime, if you find homologs with FoldSeek that were not identified using protein families or HMMs, I recommend running SitesBLAST on the top two hits.
