### ISSUE TITLE
Issue display alignment details after updating database.

### ISSUE THREAD

**Issue by gjerman** [morgannprice/PaperBLAST#2]
I just updated to the newest database from sept 3 2018 and build the blast db from uniq.faa
The blast results works fine but i get an error when trying to display the alignment details.

Unknown def: WP_002346770.1 at /z/www/tools/PaperBLAST/cgi/showAlign.cgi line 250.

**Comment by morgannprice** [comment]
Are you sure you are using the latest version of everything? This page works:
http://papers.genomics.lbl.gov/cgi-bin/showAlign.cgi?def1=WP_002346770.1%20hypothetical%20protein,%20partial%20[Enterococcus%20faecium]&def2=EfmE1162_2437&seq1=MKKSLISAVMVCSMTLTAVASPIAAAADDFDSQIQQQDQKIADLKNQQADAQSQIDALESQVSEINTQAQDLLAKQDTLRQESAQLVKDIADLQERIEKREDTIQKQAREAQVSNTSSNYIDAVLNADSLADAIGRVQAMTTMVKANNDLMEQQKQDKKAVEDKKAENDAKLKELAENQAALESQKGDLLSKQADLNVLKTSLAAEQATAEDKKADLNRQKAEAEAEQARIREQQRLAEQARQQAAQEKAEKEAREQAEAEAQATQASSTAQSSATEESSATQSSMTEESSSATQSSATEESTTPESSTEESTAPESSATEESTTA&acc2=WP_002346770.1
