### ISSUE TITLE
Avalibility of updated database?

### ISSUE THREAD

**Issue by gjerman** [morgannprice/PaperBLAST#3]
Thank you for a nice tool which has proven very useful in my work.
Would it be possible to make a newer prebuild database available, the current one was build in 2017. [https://figshare.com/articles/dataset/PaperBLAST_Apr2017_tar_gz/4836407]
I do realize that I could do this myself, but I am having issues getting it the build scripts to work.

**Comment by morgannprice** [comment]
The current database is always available from PaperBLAST's web site, see
https://github.com/morgannprice/PaperBLAST#download
