### ISSUE TITLE
Gapmind score vs completness?

### ISSUE THREAD

**Issue by michoug** [morgannprice/PaperBLAST#4]
Hi,
Nice tool,
I'm using the Gapmind part on a few hundred genomes in order to estimate the presence and completeness of different pathways.
I used the "rules" files with the "all" option and the score column but I'm having a bit of difficulty assessing the completeness based on this value when comparing with the Web-based tool.
Would you consider all pathways with scores above 0 or -1 to be complete or is it more complicated than that?
Thanks a lot
Best
Greg

**Comment by morgannprice** [comment]
If there are no medium- or low-confidence steps (nMed = 0 and nLo = 0) for rule = all, then that pathway is complete. If there are no low-confidence steps, then I'd say it's complete, but with medium confidence. If there are any low-confidence steps (nLo > 0), then the pathway is not complete.

But for amino acid biosynthesis pathways, you should also look at the known gaps -- if the only low-confidence steps are known gaps, then the pathway is probably complete, even if we don't know how it works. (To compute known gaps you'll need the low-confidence steps on the best path, from the steps table; the knownsim table, to see if there are any similar organisms in the reference database; and the table of known gaps, as in the KnownGap table in steps.db.)
