### ISSUE TITLE
Experimental keys on scalar is now forbidden gapsummary.pl

### ISSUE THREAD

**Issue by michoug** [morgannprice/PaperBLAST#5]
Hi
Got this errror "Experimental keys on scalar is now forbidden" when running `gapsummary.pl` due to my use of an later version of perl 5.26 which occurs at line 413.

`foreach my $ruleId (sort keys $rulePaths) {`

which can be repaired by

`foreach my $ruleId (sort keys %{$rulePaths}) {`

Best
Greg

**Comment by morgannprice** [comment]
I corrected that line, thanks.
