### ISSUE TITLE
GapMind replacement for ublast (vsearch?)

### ISSUE THREAD

**Issue by alexweisberg** [morgannprice/PaperBLAST#7]
Hi,

I have been using GapMind (AA and carbon catabolism) for my research and its really great. So thank you for developing it.

I mostly run things on a linux cluster, however sometimes it would be nice to run it on my macbook. However, usearch/ublast is only freely available as a 32bit binary, which does not run on recent Mac OS versions or the M1 macs. I was wondering if it would be possible to replace ublast with vsearch (https://github.com/torognes/vsearch) or a regular blast command if it is not present? 

Thanks!

**Comment by morgannprice** [comment]
Unfortunately, vsearch does not support DNA sequences. It should be straightforward to write a wrapper for another search tool (such as BLASTp or mmseqs2) to accept the same command-line inputs and return usearch format. For an example, see the mmseqs2-based utility in the curated_blast kbase app.

https://github.com/OGalOz/curated_blast/tree/master/lib/curated_blast/altered_files

I imagine this wrapper would work with GapMind as well, although you would also need to replace the curated.faa.udb file with a symbolic link to a fasta file. (And, it would run a lot faster if you saved the index.)

-- Morgan

**Comment by alexweisberg** [comment]
Thank you! I may look into writing a wrapper.

**Comment by morgannprice** [comment]
gapsearch.pl and gaprevsearch.pl now have a -diamond option. Also see
gaps/SETUP

**Comment by alexweisberg** [comment]
Excellent, thank you for implementing this!

-Alex
