### ISSUE TITLE
feature request: find dependency executables in PATH

### ISSUE THREAD

**Issue by alexweisberg** [morgannprice/PaperBLAST#8]
Hi,

I was wondering if there was a particular reason the location of usearch, hmmer, and the blast executables are hardcoded in a specific location (bin and bin/blast)? Would it be possible to modify GapMind to find the blast executables in the environment/PATH instead? It seems like that would make it a lot easier to install or incorporate in a pipeline if they were pulled from the PATH. Thanks!

**Comment by morgannprice** [comment]
I don't have root access to the web server I use, so putting executables on the path is not convenient. It's only a few steps to symlink the executables into bin. If anyone wants to write a script to do that step, it would be straightforward enough.
