### ISSUE TITLE
How to submit multiple files?

### ISSUE THREAD

**Issue by wanxn518** [morgannprice/PaperBLAST#9]
Hello, dear GapMind team.

Thank you for developing this useful tool GapMind, it helps us a lot in our work!

When submitting a task on this site, you usually have to select the protein files of a single genome in a folder and then get the results in a few seconds, but how do you run it in large batches, for example, is it possible to just submit a folder, annotate 500 files in the folder and output the results.

Looking forward to hearing from you and thank you sincerely in advance.

Best,
xnw

**Comment by morgannprice** [comment]
The web site does not support analysis of many genomes. If you want to do that, I suggest installing the code base and running GapMind from the command line. See gaps/SETUP. Also, it'll probably be more convenient to use DIAMOND instead of usearch.
